package de.hs.da.hskleinanzeigen.controller;

import de.hs.da.hskleinanzeigen.domain.*;
import de.hs.da.hskleinanzeigen.repository.AdvertisementRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;
import java.util.Optional;

@RestController
public class AdvertisementController{
    // This means to get the bean called Repository Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private AdvertisementRepository advertisementRepository;

    @Autowired
    private CategoryController categoryController;

    @Autowired
    private UserController userController;

    @PostMapping(path="/api/advertisements") // Map ONLY POST Requests
    @ResponseBody
    public ResponseEntity<AD> addNewAdvertisement (@RequestBody AD advertisement) {
        if(advertisement.getType() == null || advertisement.getCategory() == null || advertisement.getCategory().getID() == null || advertisement.getTitle() == null
                || advertisement.getDescription() == null || advertisement.getUser() == null ||  advertisement.getUser().getId() == null ){
            return new ResponseEntity<>(advertisement, HttpStatus.BAD_REQUEST);
        }
        // @ResponseBody means the returned String is the response, not a view name
        if(categoryController.getCategoryByID(advertisement.getCategory().getID()).isEmpty()){
            return new ResponseEntity<>(advertisement, HttpStatus.BAD_REQUEST);
        }

        if(!userController.getUserByID(advertisement.getUser().getId()).hasBody()){
            return new ResponseEntity<>(advertisement, HttpStatus.BAD_REQUEST);
        }
        Category category = categoryController.getCategoryByID(advertisement.getCategory().getID()).get();
        User user = userController.getUserByID(advertisement.getUser().getId()).getBody();

        advertisement.setCategory(category);
        advertisement.setUser(user);
        advertisementRepository.save(advertisement);
        return new ResponseEntity<>(advertisement, HttpStatus.CREATED);
    }

    @GetMapping("/api/advertisements/{id}")
    public Optional<AD> getAdvertisementByID(@PathVariable int id) {
        Optional<AD> advertisement = advertisementRepository.findById(id);
        if(advertisement.isEmpty()){
            throw new NotFoundException("Advertisement with the id: "+id+" is not found");
        }
        return advertisementRepository.findById(id);
    }

    @GetMapping(path="/api/advertisements")
    @ResponseBody
    public ResponseEntity<Page> getAlladvertisements(@RequestParam(required = false) Type type, @RequestParam(required = false , defaultValue = "-1") int category, @RequestParam(required = false , defaultValue = "-1") int priceFrom, @RequestParam(required = false, defaultValue = "-1") int priceTo, @RequestParam(defaultValue = "-1") int pageStart, @RequestParam(defaultValue = "-1") int pageSize) {
        if(pageSize < 0 || pageStart < 0){
            return new ResponseEntity<>(null, HttpStatus.BAD_REQUEST);
        }

        PageRequest pr = PageRequest.of(pageStart, pageSize );
        List<AD> filteredList = advertisementRepository.findAll();

        if(type != null){
            List<AD> filterType =  advertisementRepository.findByType(type,pr);
            filteredList.retainAll(filterType);
        }

        if(category != -1){
            List<AD> filterCategory =  advertisementRepository.findByCategory_ID(category,pr);
            filteredList.retainAll(filterCategory);
        }

        if(priceFrom != -1 && priceTo != -1){
            List<AD> filterPriceFromTo =  advertisementRepository.findByPriceFromTo(priceFrom,priceTo,pr);
            filteredList.retainAll(filterPriceFromTo);
        }

        if (filteredList.isEmpty())
        {
            return new ResponseEntity<>(null, HttpStatus.NO_CONTENT);
        }

        Page<AD> page = new PageImpl<>(filteredList);
        return new ResponseEntity<>(page, HttpStatus.OK);
    }
}
